### ISSUE TITLE
Am I missing something with the install?

### ISSUE THREAD

**Issue by snazzybunny** [nibroc/hubot-stocks#4]
Hello, thanks for the script. I followed the instructions and have the following error when I call hubot stock aapl: 

```
[Sat Feb 03 2018 22:06:27 GMT-0500 (EST)] ERROR TypeError: Cannot read property 'results' of undefined
  at parseQuoteForSymbol (/home/andyph666/myhubot/node_modules/hubot-stocks/src/service/stock.coffee:12:21, <js>:18:30)
  at /home/andyph666/myhubot/node_modules/hubot-stocks/src/service/stock.coffee:45:11, <js>:57:28
  at /home/andyph666/myhubot/node_modules/hubot-stocks/src/service/stock.coffee:9:5, <js>:12:14
  at IncomingMessage.<anonymous> (/home/andyph666/myhubot/node_modules/scoped-http-client/src/index.js:95:22)
  at IncomingMessage.emit (events.js:165:20)
  at endReadableNT (_stream_readable.js:1101:12)
  at process._tickCallback (internal/process/next_tick.js:152:19)
```

Has anyone come across this problem? Thanks.

**Comment by nibroc** [comment]
The Yahoo Finance API shutdown, so currently this is broken. There was some talk in #3  about moving to another API, but that hasn't been done yet. Until then, this is unfortunately broken.

**Comment by snazzybunny** [comment]
Ah okay, thanks! This is similar and more recently updated: https://github.com/gyoza/hubot-stocks-googlesource, although I am also getting errors with that repo.
